openapi: 3.0.3
info:
    title: Mobilly Test
    description: Mobilly Test homework3
    version: 1.0.0
servers:
    -   url: 'http://mobilly_test.local/'
paths:
    /:
        get:
            tags:
                - info
            summary: Task description
            responses:
                '200':
                    description: Task description
    /list:
        get:
            tags:
                - Stations
            summary: Stations list
            responses:
                '200':
                    description: Stations list
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/List'
                '401':
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                -   bearerAuth: [ ]

    /details/{id}:
        get:
            tags:
                - Station Details
            summary: Station details
            parameters:
                -   name: id
                    in: path
                    description: ID of station to return
                    required: true
                    schema:
                        type: string
            responses:
                '200':
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Details'
                '400':
                    description: Invalid ID supplied
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '404':
                    description: Station not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                -   bearerAuth: [ ]
    /details:
        get:
            tags:
                - Station Details
            summary: Station details
            parameters:
                -   name: id
                    in: query
                    description: ID of station to return
                    required: true
                    schema:
                        type: string
            responses:
                '200':
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Details'
                '400':
                    description: Invalid ID supplied
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '404':
                    description: Station not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                -   bearerAuth: [ ]
components:
    schemas:
        Error:
            required:
                - success
                - Error
            type: object
            properties:
                success:
                    type: boolean
                    example: false
                Error:
                    type: object
                    properties:
                        message:
                            type: string
                            example: Error message
                        __type:
                            type: string
                            example: Type of Error
        List:
            required:
                - success
                - result
            type: object
            properties:
                success:
                    type: boolean
                    example: true
                result:
                    type: array
                    items:
                        type: object
                        properties:
                            station_id:
                                type: string
                                example: RIVE99PA
                            name:
                                type: string
                                example: Ventspils
        Details:
            required:
                - success
                - result
            type: object
            properties:
                success:
                    type: boolean
                    example: true
                result:
                    type: object
                    properties:
                        _id:
                            type: integer
                            example: 1
                        STATION_ID:
                            type: string
                            example: "RIVE99PA"
                        NAME:
                            type: string
                            example: "Ventspils"
                        WMO_ID:
                            type: integer
                            example: 26314
                        BEGIN_DATE:
                            type: string
                            example: "1873-01-01T00:00:00"
                        END_DATE:
                            type: string
                            example: "3999-12-31T23:59:00"
                        LATITUDE:
                            type: integer
                            example: 572344
                        LONGITUDE:
                            type: integer
                            example: 213214
                        GAUSS1:
                            type: number
                            example: 352000.31
                        GAUSS2:
                            type: number
                            example: 364103.86
                        GEOGR1:
                            type: number
                            example: 21.5372
                        GEOGR2:
                            type: number
                            example: 57.3956
                        ELEVATION:
                            type: number
                            example: 2.33
                        ELEVATION_PRESSURE:
                            type: number
                            example: 3.9
                        rank:
                            type: number
                            example: 0.0573088

    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
security:
    - bearerAuth: []
